package assignment01;

public enum TokenTypes {
	WORD, NUMBER, SEPARATOR, WHILE, IF, DO, FOR, BREAK, CONTINUE, ELSE, RETURN, BEGIN, END, PRINT, PRINTF, NEXT, IN,
	DELETE, GETLINE, EXIT, NEXTFILE, FUNCTION, STRINGLITERAL, REGEXPATTERN, GREATEROREQUAL, INCREMENT, DECREMENT,
	LESSOREQUAL, EQUALTO, NOTEQUALTO, EXPONENTASSIGN, MODULUSASSIGN, MULTIPLYASSIGN, DIVIDEASSIGN, ADDASSIGN,
	SUBTRACTASSIGN, NOMATCH, AND, APPEND, OR, LEFTBRACE, RIGHTBRACE, LEFTBRACKET, RIGHTBRACKET, LEFTPARENTHESIS,
	RIGHTPARENTHESIS, DOLLAR, MATCH, EQUALS, LESSTHAN, GREATERTHAN, NOT, PLUS, EXPONENT, MINUS, QUESTIONMARK, COLON,
	MULTIPLY, DIVIDE, MODULUS, PIPE, COMMA
}
